[viewer]
    Title = "伟子时代Go语言博客"
    Description = "伟子时代Go语言博客"
    Logo = "/resource/images/logo.png"
    Navigation = ["首页","/", "GO语言","/golang", "归档","/pigeonhole", "关于","/about"]
    Bilibili = "https://space.bilibili.com/473844125"
    Zhihu = "https://www.zhihu.com/people/ma-shen-zhi-lu"
    Avatar = "https://gimg2.baidu.com/image_search/src=http%3A%2F%2Finews.gtimg.com%2Fnewsapp_bt%2F0%2F13147603927%2F1000.jpg&refer=http%3A%2F%2Finews.gtimg.com&app=2002&size=f9999,10000&q=a80&n=0&g=0n&fmt=jpeg?sec=1647242040&t=c6108010ed46b4acebe18955acdd2d24"
    UserName = "伟子时代"
    UserDesc = "长得非常帅的程序员"
[system]
    CdnURL = "https://static.mszlu.com/goblog/es6/md-assets"
    QiniuAccessKey = "60d8chTEk_fQZJjFcXvLcdVmP2CNiNQIcilHg49H"
    QiniuSecretKey = "NjU70fQPjdslSlGdoQmglFoM5-ycLwmx7JKHXno4"
    Valine = true
    ValineAppid = "ddEFySz9aeJflWy6PziluaGa-gzGzoHsz"
    ValineAppkey = "d4EnWJdHSrERtqRq9D7mjZMz"
    ValineServerURL = "https://ddefysz9.lc-cn-n1-shared.com"